flags: {}
packages:
- '.'
- location:
    git: git@github.com:mzini/monad-trace
    commit: b75ce1b391cbdd14917feeee95166d55bef5c823
extra-deps:
- smtlib2-0.3.1
- atto-lisp-0.2.2.2
- data-fix-0.0.3
resolver: lts-5.10
